export const JWT_SECRET = 'JWT_SECRET';
export const DATABASE_HOST = 'DATABASE_HOST';
export const DATABASE_PORT = 'DATABASE_PORT';
export const DATABASE_USERNAME = 'DATABASE_USERNAME';
export const DATABASE_PASSWORD = 'DATABASE_PASSWORD';
export const DATABASE_NAME = 'DATABASE_NAME';
export const DATABASE_SCHEMA = 'DATABASE_SCHEMA';
export const API_PORT = 'API_PORT';
export const FRONTEND_URL = 'FRONTEND_URL';
export const UPLOAD_FOLDER = 'UPLOAD_FOLDER';
export const SENDER_EMAIL_ADDRESS = 'SENDER_EMAIL_ADDRESS';

// Default user constants
export const DEFAULT_USER_NAME = 'DEFAULT_USER_NAME';
export const DEFAULT_USER_LASTNAME = 'DEFAULT_USER_LASTNAME';
export const DEFAULT_USER_EMAIL = 'DEFAULT_USER_EMAIL';
export const DEFAULT_USER_PASSWORD = 'DEFAULT_USER_PASSWORD';
export const DEFAULT_USER_STATUS = 'DEFAULT_USER_STATUS';
export const DEFAULT_USER_TIMEZONE = 'DEFAULT_USER_TIMEZONE';
export const STATIC_FILES_FOLDER_PATH = 'STATIC_FILES_FOLDER_PATH';