import { Component, Input, OnInit } from '@angular/core';
import {FormControl, FormGroup, FormGroupDirective } from '@angular/forms';
import { Observable } from 'rxjs';
import { map, startWith } from 'rxjs/operators';

@Component({
    selector: 'app-dynamic-timezone',
    templateUrl: './dynamic-timezone.component.html',
    styleUrls: ['./dynamic-timezone.component.css']
})
export class DynamicTimezoneComponent implements OnInit {

    @Input() field: any;
    formName!: FormGroup;
    filteredZonasHorarias!: Observable<any[]>;
    control = new FormControl('')

    zonasHorarias = [
        "(GMT-11:00) Hora de Niue",
        "(GMT-11:00) Hora estándar de Samoa",
        "(GMT-10:00) Hora de Hawái-Aleutianas",
        "(GMT-10:00) Hora de Tahití",
        "(GMT-10:00) Hora estándar de Hawái-Aleutianas",
        "(GMT-10:00) Hora estándar de las islas Cook",
        "(GMT-09:30) Hora de Marquesas",
        "(GMT-09:00) Hora de Alaska - Anchorage",
        "(GMT-09:00) Hora de Alaska - Juneau",
        "(GMT-09:00) Hora de Alaska - Metlakatla",
        "(GMT-09:00) Hora de Alaska - Nome",
        "(GMT-09:00) Hora de Alaska - Sitka",
        "(GMT-09:00) Hora de Alaska - Yakutat",
        "(GMT-09:00) Hora de Gambier",
        "(GMT-08:00) Hora de Pitcairn",
        "(GMT-08:00) Hora del Pacífico - Los Ángeles",
        "(GMT-08:00) Hora del Pacífico - Tijuana",
        "(GMT-08:00) Hora del Pacífico - Vancouver",
        "(GMT-07:00) Hora de la montaña - Boise",
        "(GMT-07:00) Hora de la montaña - Cambridge Bay",
        "(GMT-07:00) Hora de la montaña - Ciudad Juárez",
        "(GMT-07:00) Hora de la montaña - Denver",
        "(GMT-07:00) Hora de la montaña - Edmonton",
        "(GMT-07:00) Hora de la montaña - Edmonton",
        "(GMT-07:00) Hora de la montaña - Inuvik",
        "(GMT-07:00) Hora de Yukón - Dawson",
        "(GMT-07:00) Hora de Yukón - Whitehorse",
        "(GMT-07:00) Hora estándar de la montaña - Dawson Creek",
        "(GMT-07:00) Hora estándar de la montaña - Fuerte Nelson",
        "(GMT-07:00) Hora estándar de la montaña - Phoenix",
        "(GMT-07:00) Hora estándar del Pacífico de México - Hermosillo",
        "(GMT-07:00) Hora estándar del Pacífico de México - Mazatlán",
        "(GMT-06:00) Hora central - Beulah, Dakota del Norte",
        "(GMT-06:00) Hora central - Center, Dakota del Norte",
        "(GMT-06:00) Hora central - Chicago",
        "(GMT-06:00) Hora central - Knox, Indiana",
        "(GMT-06:00) Hora central - Matamoros",
        "(GMT-06:00) Hora central - Menominee",
        "(GMT-06:00) Hora central - New Salem, Dakota del Norte",
        "(GMT-06:00) Hora central - Ojinaga",
        "(GMT-06:00) Hora central - Rankin Inlet",
        "(GMT-06:00) Hora central - Resolute",
        "(GMT-06:00) Hora central - Tell City, Indiana",
        "(GMT-06:00) Hora central - Winnipeg",
        "(GMT-06:00) Hora central - Winnipeg",
        "(GMT-06:00) Hora de Galápagos",
        "(GMT-06:00) Hora estándar central - Bahía de Banderas",
        "(GMT-06:00) Hora estándar central - Belice",
        "(GMT-06:00) Hora estándar central - Chihuahua",
        "(GMT-06:00) Hora estándar central - Ciudad de México",
        "(GMT-06:00) Hora estándar central - Costa Rica",
        "(GMT-06:00) Hora estándar central - El Salvador",
        "(GMT-06:00) Hora estándar central - Guatemala",
        "(GMT-06:00) Hora estándar central - Managua",
        "(GMT-06:00) Hora estándar central - Mérida",
        "(GMT-06:00) Hora estándar central - Monterrey",
        "(GMT-06:00) Hora estándar central - Regina",
        "(GMT-06:00) Hora estándar central - Swift Current",
        "(GMT-06:00) Hora estándar central - Tegucigalpa",
        "(GMT-05:00) Hora de Cuba",
        "(GMT-05:00) Hora de Ecuador",
        "(GMT-05:00) Hora de la Isla de Pascua",
        "(GMT-05:00) Hora estándar de Acre - Eirunepé",
        "(GMT-05:00) Hora estándar de Acre - Río Branco",
        "(GMT-05:00) Hora estándar de Colombia",
        "(GMT-05:00) Hora estándar de Perú",
        "(GMT-05:00) Hora estándar oriental - Cancún",
        "(GMT-05:00) Hora estándar oriental - Jamaica",
        "(GMT-05:00) Hora estándar oriental - Panamá",
        "(GMT-05:00) Hora oriental - Detroit",
        "(GMT-05:00) Hora oriental - Gran Turca",
        "(GMT-05:00) Hora oriental - Indianápolis",
        "(GMT-05:00) Hora oriental - Iqaluit",
        "(GMT-05:00) Hora oriental - Iqaluit",
        "(GMT-05:00) Hora oriental - Louisville",
        "(GMT-05:00) Hora oriental - Marengo, Indiana",
        "(GMT-05:00) Hora oriental - Monticello, Kentucky",
        "(GMT-05:00) Hora oriental - Nueva York",
        "(GMT-05:00) Hora oriental - Petersburg, Indiana",
        "(GMT-05:00) Hora oriental - Puerto Príncipe",
        "(GMT-05:00) Hora oriental - Toronto",
        "(GMT-05:00) Hora oriental - Toronto",
        "(GMT-05:00) Hora oriental - Toronto",
        "(GMT-05:00) Hora oriental - Vevay, Indiana",
        "(GMT-05:00) Hora oriental - Vincennes, Indiana",
        "(GMT-05:00) Hora oriental - Winamac, Indiana",
        "(GMT-04:00) Hora de Bolivia",
        "(GMT-04:00) Hora de Guyana",
        "(GMT-04:00) Hora de Venezuela",
        "(GMT-04:00) Hora del Atlántico - Bermudas",
        "(GMT-04:00) Hora del Atlántico - Glace Bay",
        "(GMT-04:00) Hora del Atlántico - Goose Bay",
        "(GMT-04:00) Hora del Atlántico - Halifax",
        "(GMT-04:00) Hora del Atlántico - Moncton",
        "(GMT-04:00) Hora del Atlántico - Thule",
        "(GMT-04:00) Hora estándar del Amazonas - Boa Vista",
        "(GMT-04:00) Hora estándar del Amazonas - Campo Grande",
        "(GMT-04:00) Hora estándar del Amazonas - Cuiabá",
        "(GMT-04:00) Hora estándar del Amazonas - Manaos",
        "(GMT-04:00) Hora estándar del Amazonas - Porto Velho",
        "(GMT-04:00) Hora estándar del Atlántico - Barbados",
        "(GMT-04:00) Hora estándar del Atlántico - Martinica",
        "(GMT-04:00) Hora estándar del Atlántico - Puerto Rico",
        "(GMT-04:00) Hora estándar del Atlántico - Santo Domingo",
        "(GMT-03:30) Hora de Terranova",
        "(GMT-03:00) Hora de Chile",
        "(GMT-03:00) Hora de la Guayana Francesa",
        "(GMT-03:00) Hora de Palmer",
        "(GMT-03:00) Hora de Paraguay",
        "(GMT-03:00) Hora de Punta Arenas",
        "(GMT-03:00) Hora de Rothera",
        "(GMT-03:00) Hora de San Pedro y Miquelón",
        "(GMT-03:00) Hora de Surinam",
        "(GMT-03:00) Hora estándar de Argentina - Buenos Aires",
        "(GMT-03:00) Hora estándar de Argentina - Catamarca",
        "(GMT-03:00) Hora estándar de Argentina - Córdoba",
        "(GMT-03:00) Hora estándar de Argentina - Jujuy",
        "(GMT-03:00) Hora estándar de Argentina - La Rioja",
        "(GMT-03:00) Hora estándar de Argentina - Mendoza",
        "(GMT-03:00) Hora estándar de Argentina - Río Gallegos",
        "(GMT-03:00) Hora estándar de Argentina - Salta",
        "(GMT-03:00) Hora estándar de Argentina - San Juan",
        "(GMT-03:00) Hora estándar de Argentina - San Luis",
        "(GMT-03:00) Hora estándar de Argentina - Tucumán",
        "(GMT-03:00) Hora estándar de Argentina - Ushuaia",
        "(GMT-03:00) Hora estándar de Brasilia - Araguaína",
        "(GMT-03:00) Hora estándar de Brasilia - Bahía",
        "(GMT-03:00) Hora estándar de Brasilia - Belén",
        "(GMT-03:00) Hora estándar de Brasilia - Fortaleza",
        "(GMT-03:00) Hora estándar de Brasilia - Maceió",
        "(GMT-03:00) Hora estándar de Brasilia - Recife",
        "(GMT-03:00) Hora estándar de Brasilia - Santarém",
        "(GMT-03:00) Hora estándar de Brasilia - São Paulo",
        "(GMT-03:00) Hora estándar de las Islas Malvinas",
        "(GMT-03:00) Hora estándar de Uruguay",
        "(GMT-02:00) Hora de Georgia del Sur",
        "(GMT-02:00) Hora de Groenlandia occidental",
        "(GMT-02:00) Hora estándar de Fernando de Noronha",
        "(GMT-01:00) Hora de Groenlandia oriental",
        "(GMT-01:00) Hora de las Azores",
        "(GMT-01:00) Hora estándar de Cabo Verde",
        "(GMT+00:00) Hora de Europa del Oeste - Islas Canarias",
        "(GMT+00:00) Hora de Europa del Oeste - Islas Feroe",
        "(GMT+00:00) Hora de Europa del Oeste - Lisboa",
        "(GMT+00:00) Hora de Europa del Oeste - Madeira",
        "(GMT+00:00) Hora de Irlanda",
        "(GMT+00:00) Hora de Reino Unido",
        "(GMT+00:00) Hora de Troll",
        "(GMT+00:00) Hora del meridiano de Greenwich",
        "(GMT+00:00) Hora del meridiano de Greenwich - Abiyán",
        "(GMT+00:00) Hora del meridiano de Greenwich - Bisáu",
        "(GMT+00:00) Hora del meridiano de Greenwich - Danmarkshavn",
        "(GMT+00:00) Hora del meridiano de Greenwich - Monrovia",
        "(GMT+00:00) Hora del meridiano de Greenwich - Reikiavik",
        "(GMT+00:00) Hora del meridiano de Greenwich - Santo Tomé",
        "(GMT+00:00) Hora universal coordinada",
        "(GMT+01:00) Hora de Europa central - Ámsterdam",
        "(GMT+01:00) Hora de Europa central - Andorra",
        "(GMT+01:00) Hora de Europa central - Belgrado",
        "(GMT+01:00) Hora de Europa central - Berlín",
        "(GMT+01:00) Hora de Europa central - Bruselas",
        "(GMT+01:00) Hora de Europa central - Budapest",
        "(GMT+01:00) Hora de Europa central - Ceuta",
        "(GMT+01:00) Hora de Europa central - Copenhague",
        "(GMT+01:00) Hora de Europa central - Estocolmo",
        "(GMT+01:00) Hora de Europa central - Gibraltar",
        "(GMT+01:00) Hora de Europa central - Luxemburgo",
        "(GMT+01:00) Hora de Europa central - Madrid",
        "(GMT+01:00) Hora de Europa central - Malta",
        "(GMT+01:00) Hora de Europa central - Mónaco",
        "(GMT+01:00) Hora de Europa central - Oslo",
        "(GMT+01:00) Hora de Europa central - París",
        "(GMT+01:00) Hora de Europa central - Praga",
        "(GMT+01:00) Hora de Europa central - Roma",
        "(GMT+01:00) Hora de Europa central - Tirana",
        "(GMT+01:00) Hora de Europa central - Varsovia",
        "(GMT+01:00) Hora de Europa central - Viena",
        "(GMT+01:00) Hora de Europa central - Zúrich",
        "(GMT+01:00) Hora de Marruecos",
        "(GMT+01:00) Hora de Sáhara Occidental",
        "(GMT+01:00) Hora estándar de África occidental - Lagos",
        "(GMT+01:00) Hora estándar de África occidental - Yamena",
        "(GMT+01:00) Hora estándar de Europa central - Argel",
        "(GMT+01:00) Hora estándar de Europa central - Túnez",
        "(GMT+02:00) Hora de África central - Jartum",
        "(GMT+02:00) Hora de África central - Juba",
        "(GMT+02:00) Hora de África central - Maputo",
        "(GMT+02:00) Hora de África central - Windhoek",
        "(GMT+02:00) Hora de Europa del Este - Atenas",
        "(GMT+02:00) Hora de Europa del Este - Beirut",
        "(GMT+02:00) Hora de Europa del Este - Bucarest",
        "(GMT+02:00) Hora de Europa del Este - Chisináu",
        "(GMT+02:00) Hora de Europa del Este - El Cairo",
        "(GMT+02:00) Hora de Europa del Este - Gaza",
        "(GMT+02:00) Hora de Europa del Este - Hebrón",
        "(GMT+02:00) Hora de Europa del Este - Helsinki",
        "(GMT+02:00) Hora de Europa del Este - Kiev",
        "(GMT+02:00) Hora de Europa del Este - Kiev",
        "(GMT+02:00) Hora de Europa del Este - Kiev",
        "(GMT+02:00) Hora de Europa del Este - Nicosia",
        "(GMT+02:00) Hora de Europa del Este - Riga",
        "(GMT+02:00) Hora de Europa del Este - Sofía",
        "(GMT+02:00) Hora de Europa del Este - Tallin",
        "(GMT+02:00) Hora de Europa del Este - Vilna",
        "(GMT+02:00) Hora de Famagusta",
        "(GMT+02:00) Hora de Israel",
        "(GMT+02:00) Hora de Sudáfrica",
        "(GMT+02:00) Hora estándar de Europa del Este - Kaliningrado",
        "(GMT+02:00) Hora estándar de Europa del Este - Trípoli",
        "(GMT+03:00) Hora de África oriental",
        "(GMT+03:00) Hora de Jordania",
        "(GMT+03:00) Hora de Kírov",
        "(GMT+03:00) Hora de Siria",
        "(GMT+03:00) Hora de Turquía",
        "(GMT+03:00) Hora estándar de Arabia - Bagdad",
        "(GMT+03:00) Hora estándar de Arabia - Catar",
        "(GMT+03:00) Hora estándar de Arabia - Riad",
        "(GMT+03:00) Hora estándar de Moscú - Minsk",
        "(GMT+03:00) Hora estándar de Moscú - Moscú",
        "(GMT+03:00) Hora estándar de Moscú - Simferópol",
        "(GMT+03:00) Hora estándar de Volgogrado",
        "(GMT+03:30) Hora estándar de Irán",
        "(GMT+04:00) Hora de Astracán",
        "(GMT+04:00) Hora de Reunión",
        "(GMT+04:00) Hora de Sarátov",
        "(GMT+04:00) Hora de Seychelles",
        "(GMT+04:00) Hora de Uliánovsk",
        "(GMT+04:00) Hora estándar de Armenia",
        "(GMT+04:00) Hora estándar de Azerbaiyán",
        "(GMT+04:00) Hora estándar de Georgia",
        "(GMT+04:00) Hora estándar de Mauricio",
        "(GMT+04:00) Hora estándar de Samara",
        "(GMT+04:00) Hora estándar del Golfo",
        "(GMT+04:30) Hora de Afganistán",
        "(GMT+05:00) Hora de Kazajistán occidental - Aktau",
        "(GMT+05:00) Hora de Kazajistán occidental - Aktobe",
        "(GMT+05:00) Hora de Kazajistán occidental - Atyrau",
        "(GMT+05:00) Hora de Kazajistán occidental - Kyzylorda",
        "(GMT+05:00) Hora de Kazajistán occidental - Oral",
        "(GMT+05:00) Hora de las Tierras Australes y Antárticas Francesas",
        "(GMT+05:00) Hora de Maldivas",
        "(GMT+05:00) Hora de Mawson",
        "(GMT+05:00) Hora de Tayikistán",
        "(GMT+05:00) Hora estándar de Ekaterimburgo",
        "(GMT+05:00) Hora estándar de Pakistán",
        "(GMT+05:00) Hora estándar de Turkmenistán",
        "(GMT+05:00) Hora estándar de Uzbekistán - Samarcanda",
        "(GMT+05:00) Hora estándar de Uzbekistán - Taskent",
        "(GMT+05:30) Hora de India - Calcuta",
        "(GMT+05:30) Hora de India - Colombo",
        "(GMT+05:45) Hora de Nepal",
        "(GMT+06:00) Hora de Bután",
        "(GMT+06:00) Hora de Kazajistán oriental - Almaty",
        "(GMT+06:00) Hora de Kazajistán oriental - Kostanái",
        "(GMT+06:00) Hora de Kirguistán",
        "(GMT+06:00) Hora de Ürümqi",
        "(GMT+06:00) Hora de Vostok",
        "(GMT+06:00) Hora del océano Índico",
        "(GMT+06:00) Hora estándar de Bangladés",
        "(GMT+06:00) Hora estándar de Omsk",
        "(GMT+06:30) Hora de Islas Cocos",
        "(GMT+06:30) Hora de Myanmar (Birmania)",
        "(GMT+07:00) Hora de Barnaúl",
        "(GMT+07:00) Hora de Davis",
        "(GMT+07:00) Hora de Indochina - Bangkok",
        "(GMT+07:00) Hora de Indochina - Ciudad Ho Chi Minh",
        "(GMT+07:00) Hora de Indonesia occidental - Pontianak",
        "(GMT+07:00) Hora de Indonesia occidental - Yakarta",
        "(GMT+07:00) Hora de la Isla de Navidad",
        "(GMT+07:00) Hora de Tomsk",
        "(GMT+07:00) Hora estándar de Hovd",
        "(GMT+07:00) Hora estándar de Krasnoyarsk - Krasnoyarsk",
        "(GMT+07:00) Hora estándar de Krasnoyarsk - Novokuznetsk",
        "(GMT+07:00) Hora estándar de Novosibirsk",
        "(GMT+08:00) Hora de Brunéi",
        "(GMT+08:00) Hora de Indonesia central",
        "(GMT+08:00) Hora de Malasia - Kuala Lumpur",
        "(GMT+08:00) Hora de Malasia - Kuching",
        "(GMT+08:00) Hora de Singapur",
        "(GMT+08:00) Hora estándar de Australia occidental",
        "(GMT+08:00) Hora estándar de China - Macao",
        "(GMT+08:00) Hora estándar de China - Shanghái",
        "(GMT+08:00) Hora estándar de Filipinas",
        "(GMT+08:00) Hora estándar de Hong Kong",
        "(GMT+08:00) Hora estándar de Irkutsk",
        "(GMT+08:00) Hora estándar de Taipéi",
        "(GMT+08:00) Hora estándar de Ulán Bator - Choibalsan",
        "(GMT+08:00) Hora estándar de Ulán Bator - Ulán Bator",
        "(GMT+08:45) Hora estándar de Australia centroccidental",
        "(GMT+09:00) Hora de Indonesia oriental",
        "(GMT+09:00) Hora de Palaos",
        "(GMT+09:00) Hora de Timor Oriental",
        "(GMT+09:00) Hora estándar de Corea - Pyongyang",
        "(GMT+09:00) Hora estándar de Corea - Seúl",
        "(GMT+09:00) Hora estándar de Japón",
        "(GMT+09:00) Hora estándar de Yakutsk - Chitá",
        "(GMT+09:00) Hora estándar de Yakutsk - Khandyga",
        "(GMT+09:00) Hora estándar de Yakutsk - Yakutsk",
        "(GMT+09:30) Hora estándar de Australia central",
        "(GMT+10:00) Hora de Chuuk",
        "(GMT+10:00) Hora de Papúa Nueva Guinea",
        "(GMT+10:00) Hora estándar de Australia oriental - Brisbane",
        "(GMT+10:00) Hora estándar de Australia oriental - Lindeman",
        "(GMT+10:00) Hora estándar de Chamorro",
        "(GMT+10:00) Hora estándar de Vladivostok - Ust-Nera",
        "(GMT+10:00) Hora estándar de Vladivostok - Vladivostok",
        "(GMT+10:30) Hora de Australia central - Adelaida",
        "(GMT+10:30) Hora de Australia central - Broken Hill",
        "(GMT+11:00) Hora de Australia oriental - Hobart",
        "(GMT+11:00) Hora de Australia oriental - Macquarie",
        "(GMT+11:00) Hora de Australia oriental - Melbourne",
        "(GMT+11:00) Hora de Australia oriental - Sídney",
        "(GMT+11:00) Hora de Bougainville",
        "(GMT+11:00) Hora de Casey",
        "(GMT+11:00) Hora de Islas Salomón",
        "(GMT+11:00) Hora de Kosrae",
        "(GMT+11:00) Hora de Lord Howe",
        "(GMT+11:00) Hora de Pohnpei",
        "(GMT+11:00) Hora de Srednekolimsk",
        "(GMT+11:00) Hora estándar de Magadán",
        "(GMT+11:00) Hora estándar de Nueva Caledonia",
        "(GMT+11:00) Hora estándar de Sajalín",
        "(GMT+11:00) Hora estándar de Vanuatu",
        "(GMT+12:00) Hora de Isla Wake",
        "(GMT+12:00) Hora de Islas Gilbert",
        "(GMT+12:00) Hora de Islas Marshall - Kwajalein",
        "(GMT+12:00) Hora de Islas Marshall - Majuro",
        "(GMT+12:00) Hora de la Isla Norfolk",
        "(GMT+12:00) Hora de Nauru",
        "(GMT+12:00) Hora de Tuvalu",
        "(GMT+12:00) Hora de Wallis y Futuna",
        "(GMT+12:00) Hora estándar de Anadyr",
        "(GMT+12:00) Hora estándar de Fiyi",
        "(GMT+12:00) Hora estándar de Kamchatka",
        "(GMT+13:00) Hora de las Islas Fénix",
        "(GMT+13:00) Hora de Nueva Zelanda",
        "(GMT+13:00) Hora de Tokelau",
        "(GMT+13:00) Hora estándar de Apia",
        "(GMT+13:00) Hora estándar de Tonga",
        "(GMT+13:45) Hora de Chatham",
        "(GMT+14:00) Hora de las Espóradas Ecuatoriales"
    ]

    constructor(private formgroupDirective: FormGroupDirective) {}

    trackByFn(index: number, item: any): any {
      return item.ab;
    }
  
    _filter(value: string): any[] {
      const filterValue = value.toLowerCase();
      return this.zonasHorarias.filter(zh => zh.toLowerCase().includes(filterValue));
    }
  
    ngOnInit() {
        this.formName = this.formgroupDirective.control;
    
        this.control = this.formName.get(this.field.fieldName) as FormControl;
    
        this.filteredZonasHorarias = this.control.valueChanges.pipe(
          startWith(''),
          map(value => this._filter(value || '')),
        );
      }
  }
  