import { Component, Input, OnInit } from '@angular/core';
import { FormGroup, FormGroupDirective, FormControl } from '@angular/forms';
import { Observable } from 'rxjs';
import { map, startWith } from 'rxjs/operators';

@Component({
  selector: 'app-dynamic-country',
  templateUrl: './dynamic-country.component.html',
  styleUrls: ['./dynamic-country.component.css']
})
export class DynamicCountryComponent implements OnInit {

  @Input() field: any;
  formName!: FormGroup;
  filteredCountries!: Observable<any[]>;
  control = new FormControl('')

  countries = [
    {ab: "AF", name: "Afganistán"},
    {ab: "AL", name: "Albania"},
    {ab: "DE", name: "Alemania"},
    {ab: "AD", name: "Andorra"},
    {ab: "AO", name: "Angola"},
    {ab: "AI", name: "Anguila"},
    {ab: "AG", name: "Antigua y Barbuda"},
    {ab: "SA", name: "Arabia Saudita"},
    {ab: "DZ", name: "Argelia"},
    {ab: "AR", name: "Argentina"},
    {ab: "AM", name: "Armenia"},
    {ab: "AU", name: "Australia"},
    {ab: "AT", name: "Austria"},
    {ab: "AZ", name: "Azerbaiyán"},
    {ab: "BS", name: "Bahamas"},
    {ab: "BH", name: "Bahréin"},
    {ab: "BD", name: "Bangladés"},
    {ab: "BB", name: "Barbados"},
    {ab: "BE", name: "Bélgica"},
    {ab: "BZ", name: "Belice"},
    {ab: "BJ", name: "Benín"},
    {ab: "BM", name: "Bermudas"},
    {ab: "BY", name: "Bielorrusia"},
    {ab: "BO", name: "Bolivia"},
    {ab: "BA", name: "Bosnia y Herzegovina"},
    {ab: "BW", name: "Botsuana"},
    {ab: "BR", name: "Brasil"},
    {ab: "BN", name: "Brunéi"},
    {ab: "BG", name: "Bulgaria"},
    {ab: "BF", name: "Burkina Faso"},
    {ab: "BI", name: "Burundi"},
    {ab: "BT", name: "Bután"},
    {ab: "CV", name: "Cabo Verde"},
    {ab: "KH", name: "Camboya"},
    {ab: "CM", name: "Camerún"},
    {ab: "CA", name: "Canadá"},
    {ab: "TD", name: "Chad"},
    {ab: "CL", name: "Chile"},
    {ab: "CN", name: "China"},
    {ab: "CY", name: "Chipre"},
    {ab: "VA", name: "Ciudad del Vaticano"},
    {ab: "CO", name: "Colombia"},
    {ab: "KM", name: "Comoras"},
    {ab: "CG", name: "Congo"},
    {ab: "KP", name: "Corea del Norte"},
    {ab: "KR", name: "Corea del Sur"},
    {ab: "CR", name: "Costa Rica"},
    {ab: "CI", name: "Costa de Marfil"},
    {ab: "HR", name: "Croacia"},
    {ab: "CU", name: "Cuba"},
    {ab: "DK", name: "Dinamarca"},
    {ab: "DJ", name: "Djibouti"},
    {ab: "DM", name: "Dominica"},
    {ab: "EC", name: "Ecuador"},
    {ab: "EG", name: "Egipto"},
    {ab: "SV", name: "El Salvador"},
    {ab: "AE", name: "Emiratos Árabes Unidos"},
    {ab: "ER", name: "Eritrea"},
    {ab: "SK", name: "Eslovaquia"},
    {ab: "SI", name: "Eslovenia"},
    {ab: "ES", name: "España"},
    {ab: "US", name: "Estados Unidos"},
    {ab: "EE", name: "Estonia"},
    {ab: "ET", name: "Etiopía"},
    {ab: "PH", name: "Filipinas"},
    {ab: "FI", name: "Finlandia"},
    {ab: "FJ", name: "Fiyi"},
    {ab: "FR", name: "Francia"},
    {ab: "GA", name: "Gabón"},
    {ab: "GM", name: "Gambia"},
    {ab: "GE", name: "Georgia"},
    {ab: "GH", name: "Ghana"},
    {ab: "GI", name: "Gibraltar"},
    {ab: "GD", name: "Granada"},
    {ab: "GR", name: "Grecia"},
    {ab: "GL", name: "Groenlandia"},
    {ab: "GP", name: "Guadalupe"},
    {ab: "GU", name: "Guam"},
    {ab: "GT", name: "Guatemala"},
    {ab: "GY", name: "Guayana Francesa"},
    {ab: "GN", name: "Guinea"},
    {ab: "GQ", name: "Guinea Ecuatorial"},
    {ab: "GW", name: "Guinea-Bisáu"},
    {ab: "HT", name: "Haití"},
    {ab: "NL", name: "Holanda"},
    {ab: "HN", name: "Honduras"},
    {ab: "HK", name: "Hong Kong"},
    {ab: "HU", name: "Hungría"},
    {ab: "IN", name: "India"},
    {ab: "ID", name: "Indonesia"},
    {ab: "IR", name: "Irán"},
    {ab: "IQ", name: "Iraq"},
    {ab: "IE", name: "Irlanda"},
    {ab: "BV", name: "Isla Bouvet"},
    {ab: "CX", name: "Isla Christmas"},
    {ab: "NU", name: "Isla Niue"},
    {ab: "NF", name: "Isla Norfolk"},
    {ab: "IS", name: "Islandia"},
    {ab: "KY", name: "Islas Caimán"},
    {ab: "CC", name: "Islas Cocos"},
    {ab: "CK", name: "Islas Cook"},
    {ab: "FO", name: "Islas Feroe"},
    {ab: "GS", name: "Islas Georgias del Sur y Sandwich del Sur"},
    {ab: "HM", name: "Islas Heard y McDonald"},
    {ab: "FK", name: "Islas Malvinas"},
    {ab: "MP", name: "Islas Marianas del Norte"},
    {ab: "MH", name: "Islas Marshall"},
    {ab: "UM", name: "Islas menores de Estados Unidos"},
    {ab: "PW", name: "Islas Palau"},
    {ab: "SB", name: "Islas Salomón"},
    {ab: "SJ", name: "Islas Svalbard y Jan Mayen"},
    {ab: "TK", name: "Islas Tokelau"},
    {ab: "TC", name: "Islas Turks y Caicos"},
    {ab: "VI", name: "Islas Vírgenes (Estados Unidos)"},
    {ab: "VG", name: "Islas Vírgenes (Reino Unido)"},
    {ab: "IL", name: "Israel"},
    {ab: "IT", name: "Italia"},
    {ab: "JM", name: "Jamaica"},
    {ab: "JP", name: "Japón"},
    {ab: "JO", name: "Jordania"},
    {ab: "KZ", name: "Kazajistán"},
    {ab: "KE", name: "Kenia"},
    {ab: "KG", name: "Kirguistán"},
    {ab: "KI", name: "Kiribati"},
    {ab: "KW", name: "Kuwait"},
    {ab: "LA", name: "Laos"},
    {ab: "LS", name: "Lesoto"},
    {ab: "LV", name: "Letonia"},
    {ab: "LB", name: "Líbano"},
    {ab: "LR", name: "Liberia"},
    {ab: "LY", name: "Libia"},
    {ab: "LI", name: "Liechtenstein"},
    {ab: "LT", name: "Lituania"},
    {ab: "LU", name: "Luxemburgo"},
    {ab: "MO", name: "Macao"},
    {ab: "MG", name: "Madagascar"},
    {ab: "MY", name: "Malasia"},
    {ab: "MW", name: "Malaui"},
    {ab: "MV", name: "Maldivas"},
    {ab: "ML", name: "Malí"},
    {ab: "MT", name: "Malta"},
    {ab: "MA", name: "Marruecos"},
    {ab: "MQ", name: "Martinica"},
    {ab: "MU", name: "Mauricio"},
    {ab: "MR", name: "Mauritania"},
    {ab: "YT", name: "Mayotte"},
    {ab: "MX", name: "México"},
    {ab: "FM", name: "Micronesia"},
    {ab: "MD", name: "Moldavia"},
    {ab: "MC", name: "Mónaco"},
    {ab: "MN", name: "Mongolia"},
    {ab: "MS", name: "Montserrat"},
    {ab: "MZ", name: "Mozambique"},
    {ab: "NA", name: "Namibia"},
    {ab: "NR", name: "Nauru"},
    {ab: "NP", name: "Nepal"},
    {ab: "NI", name: "Nicaragua"},
    {ab: "NE", name: "Níger"},
    {ab: "NG", name: "Nigeria"},
    {ab: "NO", name: "Noruega"},
    {ab: "NC", name: "Nueva Caledonia"},
    {ab: "NZ", name: "Nueva Zelanda"},
    {ab: "OM", name: "Omán"},
    {ab: "PK", name: "Pakistán"},
    {ab: "PW", name: "Palaos"},
    {ab: "PS", name: "Palestina"},
    {ab: "PA", name: "Panamá"},
    {ab: "PG", name: "Papúa Nueva Guinea"},
    {ab: "PY", name: "Paraguay"},
    {ab: "PE", name: "Perú"},
    {ab: "PN", name: "Pitcairn"},
    {ab: "PF", name: "Polinesia Francesa"},
    {ab: "PL", name: "Polonia"},
    {ab: "PT", name: "Portugal"},
    {ab: "PR", name: "Puerto Rico"},
    {ab: "QA", name: "Qatar"},
    {ab: "UK", name: "Reino Unido"},
    {ab: "CF", name: "República Centroafricana"},
    {ab: "CZ", name: "República Checa"},
    {ab: "ZA", name: "República de Sudáfrica"},
    {ab: "DO", name: "República Dominicana"},
    {ab: "MK", name: "República de Macedonia"},
    {ab: "RE", name: "Reunión"},
    {ab: "RW", name: "Ruanda"},
    {ab: "RO", name: "Rumania"},
    {ab: "RU", name: "Rusia"},
    {ab: "EH", name: "Sáhara Occidental"},
    {ab: "WS", name: "Samoa"},
    {ab: "AS", name: "Samoa Americana"},
    {ab: "KN", name: "San Cristóbal y Nieves"},
    {ab: "SM", name: "San Marino"},
    {ab: "ST", name: "Santo Tomé y Príncipe"},
    {ab: "VC", name: "San Vicente y las Granadinas"},
    {ab: "SH", name: "Santa Elena"},
    {ab: "LC", name: "Santa Lucía"},
    {ab: "SN", name: "Senegal"},
    {ab: "RS", name: "Serbia"},
    {ab: "SC", name: "Seychelles"},
    {ab: "SL", name: "Sierra Leona"},
    {ab: "SG", name: "Singapur"},
    {ab: "SY", name: "Siria"},
    {ab: "SO", name: "Somalia"},
    {ab: "LK", name: "Sri Lanka"},
    {ab: "SZ", name: "Suazilandia"},
    {ab: "SD", name: "Sudán"},
    {ab: "SE", name: "Suecia"},
    {ab: "CH", name: "Suiza"},
    {ab: "SR", name: "Surinam"},
    {ab: "SJ", name: "Svalbard y Jan Mayen"},
    {ab: "TH", name: "Tailandia"},
    {ab: "TW", name: "Taiwán"},
    {ab: "TZ", name: "Tanzania"},
    {ab: "TJ", name: "Tayikistán"},
    {ab: "IO", name: "Territorio Británico del Océano Índico"},
    {ab: "TF", name: "Territorios Australes Franceses"},
    {ab: "TL", name: "Timor Oriental"},
    {ab: "TG", name: "Togo"},
    {ab: "TO", name: "Tonga"},
    {ab: "TT", name: "Trinidad y Tobago"},
    {ab: "TN", name: "Túnez"},
    {ab: "TM", name: "Turkmenistán"},
    {ab: "TR", name: "Turquía"},
    {ab: "TV", name: "Tuvalu"},
    {ab: "UA", name: "Ucrania"},
    {ab: "UG", name: "Uganda"},
    {ab: "UY", name: "Uruguay"},
    {ab: "UZ", name: "Uzbekistán"},
    {ab: "VU", name: "Vanuatu"},
    {ab: "VE", name: "Venezuela"},
    {ab: "VN", name: "Vietnam"},
    {ab: "WF", name: "Wallis y Futuna"},
    {ab: "YE", name: "Yemen"},
    {ab: "DJ", name: "Yibuti"},
    {ab: "ZM", name: "Zambia"},
    {ab: "ZW", name: "Zimbabue"}
]

  constructor(private formgroupDirective: FormGroupDirective) {}

  trackByFn(index: number, item: any): any {
    return item.ab;
  }

  _filter(value: string){
    const filterValue = value.toLowerCase();
    return this.countries.filter(country => country.name.toLowerCase().includes(filterValue) || country.ab.toLowerCase().includes(filterValue));
  }

  ngOnInit() {
    this.formName = this.formgroupDirective.control;

    this.control = this.formName.get(this.field.fieldName) as FormControl;

    this.filteredCountries = this.control.valueChanges.pipe(
      startWith(''),
      map(value => this._filter(value || '')),
    );
  }
}
